name: wallpaper_bliss
description: Nature Wallpapers

publish_to: 'none'

version: 1.1+2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cached_network_image: ^2.2.0+1
  permission_handler: ^5.0.0+hotfix.4
  path_provider: ^1.6.7
  admob_flutter: '^1.0.0-beta.4'
  provider: ^4.1.3
  rate_my_app: ^0.6.1+3
  google_fonts: ^1.1.0
  launch_review: ^2.0.0
  share: ^0.6.4+3
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  # synchronized: ^2.2.0+1
  device_info: ^0.4.2+4
  outline_material_icons: ^0.1.1
  # shared_preferences: ^0.5.7+3
  # google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
